import './globals.css'
// import {Montserrat} from "@next/font/google"

export const metadata = {
  title: 'Learning Next',
  description: 'Generated by create next app',
}
// const montserrat = Monserrat({
//   weight: ['400', '700'],
//   subsets: ['latin'],
//   variable: '--font-monserrat'
// })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className='mx-32 my-12'>
        {children}
      </body>
    </html>
  )
}
